networks:
  app:
  nginx:

services:
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    image: participe-nginx
    container_name: nginx
    volumes:
      - ./:/var/www
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - nginx

  app:
    build:
      args:
        UID: 1003
        GROUP: www-data
      context: ./.docker/php-fpm
      dockerfile: Dockerfile
    image: participe-app
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
    networks:
      - app
      - nginx

  scheduler:
    image: participe-app
    container_name: scheduler
    working_dir: /var/www
    user: root
    volumes:
      - ./:/var/www
      - ./storage/logs/supervisor:/var/log
    entrypoint: ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      - app


  #CONTAINER SERVICES

  node:
    build:
      context: ./.docker/node
      dockerfile: Dockerfile
    image: participe-node
    container_name: node
    working_dir: /var/www
    volumes:
      - ./:/var/www

  composer:
    image: participe-app
    container_name: composer
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["composer"]
    networks:
      - app

  artisan:
    image: participe-app
    container_name: artisan
    working_dir: /var/www
    volumes:
      - ./:/var/www
    entrypoint: ["php", "artisan"]
    networks:
      - app