import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// import {} from '@fortawesome/free-brands-svg-icons'

import {
    faEnvelope,
    faUser,
    faUserXmark,
    faCheck,
    faCircleCheck,
    faCircleRight,
    faCircleXmark,
    faPlus,
    faMinus,
    faMagnifyingGlass,
    faTrash,
    faFileArrowDown,
    faFilePen,
    faPen,
    faArrowRightFromBracket,
    faChartLine,
    faHouseLaptop,
    faGear,
    faAngleUp,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faLightbulb,
    faCalendarDays,
    faUsers,
    faMapLocationDot,
    faArrowLeft,
    faArrowUpWideShort,
    faArrowDownWideShort,
    faSort,
    faWandSparkles,
    faSquareCheck,
    faTriangleExclamation,
    faCaretDown,
    faStepBackward,
    faChevronUp,
    faChevronLeft,
    faChevronRight,
    faChevronDown,
    faStepForward,
    faTimes,
    faPaperclip,
    faUserNurse,
} from '@fortawesome/free-solid-svg-icons'

import {
    faFileLines,
    faPaperPlane,
    faSquare,
    faCircle,
    faDotCircle,
    faHospital,
    faFileExcel,
    faFilePdf
} from '@fortawesome/free-regular-svg-icons'

library.add(
    faEnvelope,
    faSquare,
    faSquareCheck,
    faUser,
    faUserXmark,
    faCheck,
    faCircleCheck,
    faCircleXmark,
    faPlus,
    faMinus,
    faCircleRight,
    faMagnifyingGlass,
    faTrash,
    faFileLines,
    faFileArrowDown,
    faFilePen,
    faPen,
    faArrowRightFromBracket,
    faChartLine,
    faHouseLaptop,
    faGear,
    faAngleUp,
    faAngleDown,
    faAngleLeft,
    faAngleRight,
    faLightbulb,
    faCalendarDays,
    faUsers,
    faMapLocationDot,
    faPaperPlane,
    faArrowLeft,
    faArrowUpWideShort,
    faArrowDownWideShort,
    faSort,
    faWandSparkles,
    faTriangleExclamation,
    faCaretDown,
    faStepBackward,
    faChevronUp,
    faChevronLeft,
    faChevronRight,
    faChevronDown,
    faStepForward,
    faCircle,
    faDotCircle,
    faTimes,
    faPaperclip,
    faHospital,
    faUserNurse,
    faFileExcel,
    faFilePdf
)

export default FontAwesomeIcon